name: Web-Application CI

on:
    push:
        branches: [main]
        paths: ['src/**', 'package.json', '.github/workflows/main.yml']

    # Triggers workflow on pull-request events
    # pull_request:
    #     branches: [master]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '16'

            - name: Install dependencies
              run: cd web-app && npm ci

            - name: Lint
              run: cd web-app && npm run lint

            - name: Build
              run: cd web-app && npm run build

            - name: Test
              run: cd web-app && npm run test-ci
