name: Web-Application CI

on:
    push:
        branches: [main]
        paths: ['src/**', 'web-app/package.json', '.github/workflows/main.yml']

    # Triggers workflow on pull-request events
    # pull_request:
    #     branches: [master]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
env:
    dir: web-app

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '16'
                  cache: 'npm'
                  registry-url: https://npm.pkg.github.com/
                  cache-dependency-path: ${{env.dir}}/package-lock.json

            - name: Install dependencies
              run: |
                  cd ${{env.dir}}
                  npm ci
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Lint
              run: |
                  cd ${{env.dir}}
                  npm run lint

            - name: Build
              run: |
                  cd ${{env.dir}}
                  npm run build

            - name: Test
              run: |
                  cd ${{env.dir}}
                  npm run test-ci
